# Generated by Django 5.2.9 on 2026-01-07 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VENDAS_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='valortotal',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
