# Generated by Django 5.2.9 on 2026-01-08 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VENDAS_app', '0002_alter_venda_valortotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itenvenda',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='VENDAS_app.produto'),
        ),
    ]
